version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: citizen_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

  # Backend Service (Node.js + Express)
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: citizen_db
      PORT: 5000
    networks:
      - app_network
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app       # Mount backend source code
      - /usr/src/app/node_modules    # Mount node_modules as a volume

  # Frontend Service (React + Vite)
  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    environment:
      VITE_API_URL: http://localhost:5000
    networks:
      - app_network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app       # Mount frontend source code
      - /usr/src/app/node_modules     # Mount node_modules as a volume
    depends_on:
      - backend

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
