version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:9.0.1
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password      # Root password for MySQL
      - MYSQL_DATABASE=libyan_residents_abroad         # Initial database to create
      - MYSQL_USER=app_user                           # Non-root MySQL user
      - MYSQL_PASSWORD=app_user_password              # Password for the MySQL user
    ports:
      - "3306:3306"                                   # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql                        # Persist data using volumes

  # Backend Node.js/Express Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    restart: always
    ports:
      - "5000:5000"                                   # Expose backend API port
    environment:
      - DB_HOST=db                                    # Reference the 'db' service as the host
      - DB_USER=app_user
      - DB_PASSWORD=app_user_password
      - DB_NAME=libyan_residents_abroad
    depends_on:
      - db                                            # Ensure backend starts after the database

  # Frontend React (Vite) Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    restart: always
    ports:
      - "3006:3006"                                   # Expose frontend port for React
    depends_on:
      - backend                                       # Ensure frontend starts after backend

volumes:
  db_data:                                             # Persistent volume for MySQL